[package]
name = "cripplock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# gdk = { version = "0.17.1", features = ["v3_24"] }
glib = "0.17.1"
gtk = "0.17.1"
gtk-layer-shell = "0.6.1"
